// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");

var initialState = /* record */[
  /* loggedIn */false,
  /* settings */false,
  /* username */""
];

function App(Props) {
  var match = React.useReducer((function (state, action) {
          if (typeof action === "number") {
            return /* record */[
                    /* loggedIn */false,
                    /* settings */state[/* settings */1],
                    /* username */state[/* username */2]
                  ];
          } else if (action.tag) {
            return /* record */[
                    /* loggedIn */state[/* loggedIn */0],
                    /* settings */action[0],
                    /* username */state[/* username */2]
                  ];
          } else {
            return /* record */[
                    /* loggedIn */true,
                    /* settings */state[/* settings */1],
                    /* username */action[0]
                  ];
          }
        }), initialState);
  var dispatch = match[1];
  var state = match[0];
  var match$1 = React.useState((function () {
          return "";
        }));
  var settings = state[/* settings */1];
  var setUsername = match$1[1];
  var username = match$1[0];
  var onSubmit = function ($$event) {
    $$event.preventDefault();
    return Curry._1(dispatch, /* LogIn */Block.__(0, [username]));
  };
  var setUsernameHandler = function ($$event) {
    return Curry._1(setUsername, $$event.target.value);
  };
  return React.createElement("div", {
              className: "wrapper"
            }, state[/* loggedIn */0] ? React.createElement(React.Fragment, undefined, React.createElement("div", {
                        className: "heading"
                      }, "Welcome " + (username + ", you are logged in")), React.createElement("button", {
                        onClick: (function (param) {
                            return Curry._1(dispatch, /* Settings */Block.__(1, [!settings]));
                          })
                      }, settings ? "Close Settings" : "Settings"), React.createElement("button", {
                        onClick: (function (param) {
                            return Curry._1(dispatch, /* LogOut */0);
                          })
                      }, "Log Out"), settings ? React.createElement("div", {
                          className: "headingSmall"
                        }, "This is a settings page") : null) : React.createElement(React.Fragment, undefined, React.createElement("div", {
                        className: "heading"
                      }, "Logged Out"), React.createElement("form", undefined, React.createElement("input", {
                            name: "username",
                            value: username,
                            onChange: setUsernameHandler
                          }), React.createElement("button", {
                            onClick: onSubmit
                          }, "Log In"))));
}

var make = App;

exports.initialState = initialState;
exports.make = make;
/* react Not a pure module */
